// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Review struct {
	ID      string   `json:"id"`
	Body    *string  `json:"body"`
	Author  *User    `json:"author"`
	Product *Product `json:"product"`
}

func (Review) IsEntity() {}
