// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type User struct {
	ID       string     `json:"id"`
	Name     *string    `json:"name"`
	Username *string    `json:"username"`
	Birthday *time.Time `json:"birthday"`
}

func (User) IsEntity() {}
